runtime: php81
env_variables:
  APP_NAME: Laravel
  APP_ENV: local
  APP_KEY: base64:z4vCpupP+lUFBPZcAtROAn2Gbyf7WDZ+G+f+E7jmXHI=
  APP_DEBUG: true
  APP_URL: http://laravel-api.test
  APP_LOG: errorlog
  APP_LOG_LEVEL: debug
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp